### ISSUE TITLE
zoom registration worker

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/automation#15]
It should be pretty similar to the mailing list signup one, except we'll need to use JWT for auth.

**Comment by akhmerov** [comment]
~~Done, closing :tada:~~

Was too hasty and misread the issue description :facepalm:

**Comment by everthemore** [comment]
Quick question workflow for the website on this. Some possibilities:

- For each talk, have a button with 'register', that takes the user to a separate page like we have for the mailinglist-signup.
- Embed a form

Preferences?

**Comment by akhmerov** [comment]
We should track the website implementation in the other repo. At the moment I'm not 100% sure what is the better option. Some of our pages are getting crowded (speakers' corner especially fast), and we may need to restructure them.
