### ISSUE TITLE
link to application issue for video recordings

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/automation#33]
The link in my email that should take me to the application issue takes me to the general issues page. This is the link: 

`https://github.com/virtualscienceforum/virtualscienceforum/issues#193`

But it seems like it should be this

`https://github.com/virtualscienceforum/virtualscienceforum/issues/193`

Notice the slash rather than the hashtag before the issue number.

**Comment by akhmerov** [comment]
Looking at [the template](https://github.com/virtualscienceforum/automation/blob/master/host_key_rotation.py#L203), it seems that the URL is already correct. I believe you received an old version of the email sent by me manually, and I must have fixed this afterwards.
