### ISSUE TITLE
Add zoom registrants to the mailing list

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/automation#34]
This should be done using a daily cron job, where we should also move the weekly speakers' corner announcements, as well as querying the speaker for the video publication approval.

A rough implementation is available [over here](https://github.com/virtualscienceforum/automation/blob/3bfaa04c9e67627559ad16f57a31fb7cbe612cba/vsf_mailgun.py#L214-L224), only lacks filtering recent zoom meetings.

**Comment by everthemore** [comment]
FYI: I've hardcoded it to look at the last 20 meetings for now, that seemed like a reasonable number.

**Comment by akhmerov** [comment]
If we run the job daily, looking at one day is enough.
