### ISSUE TITLE
Reserving a zoom meeting

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/automation#9]
Should be triggered when a new talk is added to the talk list

We:

- Create a new zoom meeting (need to figure out for which account)
- Email the host key
- Add the zoom meeting id and the registration link to the yaml

Here we should also decide:

- Where to store the meeting parameters, and what these parameters should be.

**Comment by everthemore** [comment]
Can we close this?

**Comment by akhmerov** [comment]
Let's keep it open until we finish debugging and deploy the thing.

**Comment by everthemore** [comment]
Ok, my alternative proposal was to open separate issues. 
In that case, would you mind having a look at the "registration question patching" when you get a chance? I still cannot see the meetings we're creating via my evn+vsf@gmail account.

**Comment by akhmerov** [comment]
> I still cannot see the meetings

You should use your admin privileges, and go users → speakers' corner → meetings

> In that case, would you mind having a look at the "registration question patching" when you get a chance?

Sure

**Comment by everthemore** [comment]
> You should use your admin privileges, and go users → speakers' corner → meetings
Are they so well hidden that I can't find them? I am a 'member', does that make a difference?
<img width="391" alt="Screenshot 2020-10-12 at 14 37 09" src="https://user-images.githubusercontent.com/1933169/95747313-8c19de80-0c98-11eb-911e-1461f7e160d6.png">

**Comment by akhmerov** [comment]
![image](https://user-images.githubusercontent.com/2069677/95751337-c4242000-0c9e-11eb-83fb-e31d9876408b.png)

**Comment by akhmerov** [comment]
Ah! My bad, you weren't admin. Fixed.

**Comment by akhmerov** [comment]
I now fixed the questions

**Comment by akhmerov** [comment]
- [x] The email contains the registration URL, not join URL.

**Comment by akhmerov** [comment]
- [x] Should remove social buttons from the registration form
- [x] cannot join using the registration URL for some reason (zoom redirects me to the form, which is the same as what happens when the registration isn't recognized). That's because the registration misses required questions—I checked that making those questions optional fixes the problem.
- [x] Too many questions are required ("may we contact" and "how did you hear" shouldn't be)

**Comment by everthemore** [comment]
> * [x]  The email contains the registration URL, not join URL.

Glad you changed it back 👍

**Comment by everthemore** [comment]
> I now fixed the questions

What was the issue?

**Comment by akhmerov** [comment]
See https://github.com/virtualscienceforum/automation/commit/56daa8bc8b5f8f66a49abdc0138645906747519e: we were hitting nonexistent endpoints, and also the questions were malformatted (predefined questions have specific shortcut names).

**Comment by akhmerov** [comment]
- [ ] Before turning this on, we should disable the "I added the talk to the schedule" message by the other bot.

**Comment by everthemore** [comment]
> * [x]  Should remove social buttons from the registration form

This seems to be unsupported using the API web endpoints for meetings (as of 2019 https://devforum.zoom.us/t/disable-social-share-button-for-meetings/5170), only for webinars ('show_share_button' bool: https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/webinarcreate). Worth trying

> * [x]  cannot join using the registration URL for some reason (zoom redirects me to the form, which is the same as what happens when the registration isn't recognized). That's because the registration misses required questions—I checked that making those questions optional fixes the problem.

So you fixed this? 

> * [x]  Too many questions are required ("may we contact" and "how did you hear" shouldn't be)

Ok, want me to set req'd to False?

**Comment by akhmerov** [comment]
> This seems to be unsupported using the API web endpoints

Indeed, I confirm. This is also not returned in the data, so we'll have to live with it.

> So you fixed this?

Not yet, on it.

**Comment by akhmerov** [comment]
Fixed the registrations now.

> Before turning this on, we should disable the "I added the talk to the schedule" message by the other bot.

Instead of doing that, I'll make that other bot post the detailed instructions so that most texts are in the other repo.

**Comment by everthemore** [comment]
> Instead of doing that, I'll make that other bot post the detailed instructions so that most texts are in the other repo.

Through a workflow_dispatch?

**Comment by akhmerov** [comment]
No, just a generic checklist with no specifics, when the talk is approved.

**Comment by akhmerov** [comment]
Done, closing :tada:
